url: "https://github.com/angelina-tsuboi/ctv/releases/download/$VERSION/ctv-$VERSION_NUMBER-x86_64-apple-darwin.tar.gz"
tap: angelina-tsuboi/homebrew-ctv/Formula/ctv.rb
template: |
  class App < Formula
    desc     "$REPO_DESCRIPTION"
    homepage "$REPO_WEBSITE"
    version  "$STABLE_VERSION"
    url      "$STABLE_ASSET_URL"
    sha256   "$STABLE_ASSET_SHA256"
    
    def install
      bin.install "ctv"
    end
  end
